In [1]:
import numpy as np

# Get inputs

In [2]:
#with open("test_input.txt") as f:
with open("input.txt") as f:
    inp = f.readlines()
    inp = [line.rstrip() for line in inp]

In [3]:
inp[:2]

['427,523 -> 427,790', '94,639 -> 94,951']

In [4]:
cleaned = []
for line in inp:
    tmp = np.array([list(map(int,element.split(","))) for element in line.split(" -> ")]).flatten()
    # append if x1 = x2 or y1 = y2 - horiuzontal/vertical
    if tmp[0] == tmp[2] or tmp[1] == tmp[3]:
        cleaned.append(tmp)
        
    # append if diagonal for Q2
    elif abs(tmp[0] - tmp[2]) == abs(tmp[1] - tmp[3]):
        cleaned.append(tmp)
cleaned = np.array(cleaned)
cleaned

array([[427, 523, 427, 790],
       [ 94, 639,  94, 951],
       [757, 371, 465, 663],
       ...,
       [ 61, 804,  61, 832],
       [475, 387, 966, 878],
       [822, 740, 822, 186]])

In [5]:
cleaned = []
for line in inp:
    tmp = np.array([list(map(int,element.split(","))) for element in line.split(" -> ")]).flatten()
    # append if x1 = x2 or y1 = y2 - horiuzontal/vertical
    if tmp[0] == tmp[2] or tmp[1] == tmp[3]:
        cleaned.append(tmp)
cleaned = np.array(cleaned)
cleaned

array([[427, 523, 427, 790],
       [ 94, 639,  94, 951],
       [503, 935, 503, 148],
       ...,
       [375, 342, 375, 668],
       [ 61, 804,  61, 832],
       [822, 740, 822, 186]])

In [6]:
x1 = max(cleaned[:,0])
x2 = max(cleaned[:,2])
y1 = max(cleaned[:,1])
y2 = max(cleaned[:,3])

x = max(x1,x2) + 1
y = max(y1,y2) + 1
m = max(y,x)

In [7]:
zerod = np.zeros((m,m), dtype=int)

## Q1

In [8]:
def fill_board(board):
    for line in cleaned:
        x1,y1,x2,y2 = line
        
        # move y
        if x1 == x2:
            if y1 < y2:
                while y1 <= y2:
                    board[x1,y1] += 1
                    y1 += 1
            else:
                while y2 <= y1:
                    board[x1,y2] += 1
                    y2 += 1
        else:
            if x1 < x2:
                while x1 <= x2:
                    board[x1,y1] +=1
                    x1 += 1
            else:
                while x2 <= x1:
                    board[x2,y1] +=1
                    x2 += 1
    return board.T

In [9]:
filled = fill_board(zerod.copy())
filled

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [10]:
unique, counts = np.unique(filled, return_counts=True)
unique_counts = dict(zip(unique, counts))

In [11]:
unique_counts.pop(0)
unique_counts.pop(1)
unique_counts

{2: 7071, 3: 222, 4: 4}

In [12]:
print(f"Part 1: {sum(unique_counts.values())}")

Part 1: 7297


## Q2

In [13]:
cleaneddiag = []
for line in inp:
    tmp = np.array([list(map(int,element.split(","))) for element in line.split(" -> ")]).flatten()
    # append if diagonal for Q2
    if abs(tmp[0] - tmp[2]) == abs(tmp[1] - tmp[3]):
        cleaneddiag.append(tmp)
cleaneddiag = np.array(cleaneddiag)
cleaneddiag[:2]

array([[757, 371, 465, 663],
       [167, 754, 710, 211]])

In [14]:
def fill_board_diag(board):
    for line in cleaneddiag:
        x1,y1,x2,y2 = line
        
        # right
        if x1 < x2:
            # down
            if y1 < y2:
                while y1 <= y2:
                    board[x1,y1] += 1
                    y1 += 1
                    x1 += 1
            # up
            else:
                while y2 <= y1:
                    board[x1,y1] += 1
                    y1 -= 1
                    x1 += 1
        # left
        else:
            # down
            if y1 < y2:
                while y1 <= y2:
                    board[x1,y1] += 1
                    y1 += 1
                    x1 -= 1
            # up
            else:
                while y2 <= y1:
                    board[x1,y1] += 1
                    y1 -= 1
                    x1 -= 1
    return board.T

In [15]:
fill_board_diag(filled.T)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
unique, counts = np.unique(filled, return_counts=True)
unique_counts = dict(zip(unique, counts))

In [17]:
unique_counts.pop(0)
unique_counts.pop(1)
unique_counts

{2: 19328, 3: 1610, 4: 99, 5: 1}

In [18]:
print(f"Part 2: {sum(unique_counts.values())}")

Part 2: 21038
