In [1]:
import numpy as np

# Get inputs

In [2]:
#with open("test_input.txt") as f:
with open("input.txt") as f:
    inp = f.readlines()
    inp = [line.rstrip() for line in inp]

In [3]:
inp

['427,523 -> 427,790',
 '94,639 -> 94,951',
 '757,371 -> 465,663',
 '503,935 -> 503,148',
 '655,565 -> 655,951',
 '167,754 -> 710,211',
 '634,433 -> 245,433',
 '449,889 -> 449,509',
 '152,753 -> 207,808',
 '301,90 -> 301,982',
 '566,405 -> 482,405',
 '758,741 -> 847,652',
 '342,686 -> 921,107',
 '741,317 -> 741,533',
 '976,917 -> 976,664',
 '273,272 -> 273,899',
 '326,616 -> 326,478',
 '483,906 -> 391,814',
 '20,165 -> 20,349',
 '860,533 -> 860,137',
 '846,834 -> 846,610',
 '155,923 -> 241,923',
 '989,984 -> 17,12',
 '711,681 -> 82,52',
 '312,788 -> 312,281',
 '319,746 -> 892,746',
 '568,555 -> 757,555',
 '659,450 -> 940,450',
 '870,260 -> 870,487',
 '110,794 -> 604,794',
 '509,141 -> 509,99',
 '29,68 -> 29,713',
 '340,688 -> 820,688',
 '428,46 -> 902,520',
 '539,525 -> 539,210',
 '181,822 -> 806,822',
 '551,338 -> 551,79',
 '894,542 -> 894,151',
 '700,625 -> 700,60',
 '143,736 -> 143,770',
 '810,975 -> 54,219',
 '44,373 -> 44,514',
 '849,794 -> 120,794',
 '347,690 -> 97,440',
 '10,625

In [4]:
cleaned = []
for line in inp:
    tmp = np.array([list(map(int,element.split(","))) for element in line.split(" -> ")]).flatten()
    # append if x1 = x2 or y1 = y2 - horiuzontal/vertical
    if tmp[0] == tmp[2] or tmp[1] == tmp[3]:
        cleaned.append(tmp)
        
    # append if diagonal for Q2
    elif abs(tmp[0] - tmp[2]) == abs(tmp[1] - tmp[3]):
        cleaned.append(tmp)
cleaned = np.array(cleaned)
cleaned

array([[427, 523, 427, 790],
       [ 94, 639,  94, 951],
       [757, 371, 465, 663],
       ...,
       [ 61, 804,  61, 832],
       [475, 387, 966, 878],
       [822, 740, 822, 186]])

In [5]:
cleaned = []
for line in inp:
    tmp = np.array([list(map(int,element.split(","))) for element in line.split(" -> ")]).flatten()
    # append if x1 = x2 or y1 = y2 - horiuzontal/vertical
    if tmp[0] == tmp[2] or tmp[1] == tmp[3]:
        cleaned.append(tmp)
cleaned = np.array(cleaned)
cleaned

array([[427, 523, 427, 790],
       [ 94, 639,  94, 951],
       [503, 935, 503, 148],
       ...,
       [375, 342, 375, 668],
       [ 61, 804,  61, 832],
       [822, 740, 822, 186]])

In [6]:
x1 = max(cleaned[:,0])
x2 = max(cleaned[:,2])
y1 = max(cleaned[:,1])
y2 = max(cleaned[:,3])

x = max(x1,x2) + 1
y = max(y1,y2) + 1
m = max(y,x)

In [7]:
zerod = np.zeros((m,m), dtype=int)

## Q1

In [8]:
def fill_board(board):
    for line in cleaned:
        x1,y1,x2,y2 = line
        
        # move y
        if x1 == x2:
            if y1 < y2:
                while y1 <= y2:
                    board[x1,y1] += 1
                    y1 += 1
            else:
                while y2 <= y1:
                    board[x1,y2] += 1
                    y2 += 1
        else:
            if x1 < x2:
                while x1 <= x2:
                    board[x1,y1] +=1
                    x1 += 1
            else:
                while x2 <= x1:
                    board[x2,y1] +=1
                    x2 += 1
    return board.T

In [9]:
filled = fill_board(zerod.copy())
filled

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [10]:
unique, counts = np.unique(filled, return_counts=True)
unique_counts = dict(zip(unique, counts))

In [11]:
unique_counts.pop(0)
unique_counts.pop(1)
unique_counts

{2: 7071, 3: 222, 4: 4}

In [12]:
sum(unique_counts.values())

7297

## Q2

In [13]:
cleaneddiag = []
for line in inp:
    tmp = np.array([list(map(int,element.split(","))) for element in line.split(" -> ")]).flatten()
    # append if diagonal for Q2
    if abs(tmp[0] - tmp[2]) == abs(tmp[1] - tmp[3]):
        cleaneddiag.append(tmp)
cleaneddiag = np.array(cleaneddiag)
cleaneddiag

array([[757, 371, 465, 663],
       [167, 754, 710, 211],
       [152, 753, 207, 808],
       [758, 741, 847, 652],
       [342, 686, 921, 107],
       [483, 906, 391, 814],
       [989, 984,  17,  12],
       [711, 681,  82,  52],
       [428,  46, 902, 520],
       [810, 975,  54, 219],
       [347, 690,  97, 440],
       [375, 491, 809, 925],
       [120, 978, 958, 140],
       [623, 270, 158, 735],
       [ 45, 242, 311, 508],
       [530, 469, 433, 566],
       [ 46, 101, 877, 932],
       [607, 655, 485, 777],
       [773, 672, 461, 360],
       [457, 700, 125, 368],
       [916, 802, 181,  67],
       [849, 384, 743, 278],
       [ 17, 989, 933,  73],
       [376, 744, 178, 942],
       [ 62, 728, 589, 201],
       [588, 150, 467,  29],
       [202, 664, 751, 115],
       [519, 547, 916, 150],
       [803, 483, 380,  60],
       [823,  94,  18, 899],
       [802, 734, 415, 347],
       [103, 496, 551,  48],
       [137, 581, 707,  11],
       [501, 563, 895, 957],
       [201, 9

In [14]:
def fill_board_diag(board):
    for line in cleaneddiag:
        x1,y1,x2,y2 = line
        
        # right
        if x1 < x2:
            # down
            if y1 < y2:
                while y1 <= y2:
                    board[x1,y1] += 1
                    y1 += 1
                    x1 += 1
            # up
            else:
                while y2 <= y1:
                    board[x1,y1] += 1
                    y1 -= 1
                    x1 += 1
        # left
        else:
            # down
            if y1 < y2:
                while y1 <= y2:
                    board[x1,y1] += 1
                    y1 += 1
                    x1 -= 1
            # up
            else:
                while y2 <= y1:
                    board[x1,y1] += 1
                    y1 -= 1
                    x1 -= 1
    return board.T

In [15]:
fill_board_diag(filled.T)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
unique, counts = np.unique(filled, return_counts=True)
unique_counts = dict(zip(unique, counts))

In [17]:
unique_counts.pop(0)
unique_counts.pop(1)
unique_counts

{2: 19328, 3: 1610, 4: 99, 5: 1}

In [18]:
sum(unique_counts.values())

21038