In [166]:
import numpy as np

# Get inputs

In [193]:
#with open("test_input.txt") as f:
with open("input.txt") as f:
    inp = f.readlines()
    inp = [line.rstrip() for line in inp]

In [194]:
binalgo = [0 if x == '.' else 1 for x in inp[0]]
binimage = np.array([[0 if x == '.' else 1 for x in line] for line in inp[2:]],dtype=np.int8)

## Q1

In [216]:
def enhance(algo, image):
    
    padded_image = np.pad(image, 2, 'constant', constant_values=0)
    #print(padded_image)
    enhanced_image = np.full(padded_image.shape, 0, dtype=np.int8)
    
    for i in range(padded_image.shape[0]-2):
        x = i + 1
        for j in range(padded_image.shape[1]-2):
            y = j + 1
            
            bins = np.array([], dtype=np.int8)
            bins = np.append(bins, padded_image[x-1:x+2,y-1:y+2])
            bin_str = ''.join(bins.astype(str))
            if len(bin_str) != 9:
                print(f"BAD {bins=}")
            index = int(bin_str,2)
            enhanced_image[x,y] = algo[index]
            # print(x,y)
            # print(bin_str, algo[index])
            # print(x,y)
            # print(padded_image[x-1:x+2,y-1:y+2])
            # print(f"{index=}")
            # print(f"{algo[index]=}")
            # break
    print(f"{x=},{y=}")
    print(f"{enhanced_image.shape=}")
    return enhanced_image[1:-1,1:-1]

In [217]:
im = binimage.copy()
#with np.printoptions(threshold=np.inf): print(im)
for i in range(2):
    im = enhance(binalgo, im)
    #with np.printoptions(threshold=np.inf): print(im)
    
print(np.sum(im))

x=102,y=102
enhanced_image.shape=(104, 104)
x=104,y=104
enhanced_image.shape=(106, 106)
5575


In [192]:
with np.printoptions(threshold=np.inf):
    #print(binimage)
    print(im)

[[0 0 0 0 0 0 0 1 0]
 [0 1 0 0 1 0 1 0 0]
 [1 0 1 0 0 0 1 1 1]
 [1 0 0 0 1 1 0 1 0]
 [1 0 0 0 0 0 1 0 1]
 [0 1 0 1 1 1 1 1 0]
 [0 0 1 0 1 1 1 1 1]
 [0 0 0 1 1 0 1 1 0]
 [0 0 0 0 1 1 1 0 0]]


## Q2